# Generated by Django 3.1.2 on 2020-11-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('origin_id', models.IntegerField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_noti_set', to=settings.AUTH_USER_MODEL)),
                ('origin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_noti_set', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_noti_set', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetted_noti_set', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('actor', 'recipient', 'target_id', 'target_type', 'origin_id', 'origin_type', 'message'), name='unique_noti'),
        ),
    ]
